/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;


import Datos.clsMedidores;

import Logica.fMedidores;
import java.awt.Color;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USE
 */
public class frmMedidores extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmMedidores
     */
    public frmMedidores() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        initComponents();
        cargarTabla("", "Codigo", "Codigo", "desc");
        inhabilitar();
    }
    String accion = "null";
    boolean isActiveNuevo = false;
    boolean isActiveEditar = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMedidores = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnReporte = new javax.swing.JLabel();
        paneFormulario = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtFechaInstalacion = new javax.swing.JTextField();
        txtBarrio = new javax.swing.JTextField();
        txtCallePrincipal = new javax.swing.JTextField();
        txtCalleSecundaria = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtNumeroCasa = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        txtSocio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));

        tblMedidores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        tblMedidores.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblMedidores.setForeground(new java.awt.Color(102, 102, 102));
        tblMedidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedidores.setGridColor(new java.awt.Color(255, 255, 255));
        tblMedidores.setRowHeight(20);
        tblMedidores.setSelectionBackground(new java.awt.Color(52, 152, 219));
        tblMedidores.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblMedidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedidoresMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblMedidores);

        jPanel7.setPreferredSize(new java.awt.Dimension(150, 0));

        btnEditar.setBackground(new java.awt.Color(52, 152, 219));
        btnEditar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editarL32x32.png"))); // NOI18N
        btnEditar.setText("ACTUALIZAR");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setOpaque(true);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(150, 0));

        btnAgregar.setBackground(new java.awt.Color(52, 152, 219));
        btnAgregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregarbold32x32.png"))); // NOI18N
        btnAgregar.setText("NUEVO");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setOpaque(true);
        btnAgregar.setPreferredSize(new java.awt.Dimension(40, 15));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.setBackground(new java.awt.Color(52, 152, 219));

        jLabel7.setBackground(new java.awt.Color(52, 152, 219));
        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MEDIDORES");

        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBuscarInputMethodTextChanged(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(52, 152, 219));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar32x32.png"))); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(true);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Marca", "Nombres Socio", "Cedula Socio", "Barrio", "Calle Principal", "Fecha Instalacion", "Numero Casa" }));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CATEGORíA");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCategoria)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jPanel10.setPreferredSize(new java.awt.Dimension(150, 0));

        btnReporte.setBackground(new java.awt.Color(52, 152, 219));
        btnReporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imprimir32x32.png"))); // NOI18N
        btnReporte.setText("REPORTE");
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.setOpaque(true);
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        paneFormulario.setBackground(new java.awt.Color(255, 255, 255));
        paneFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del medidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        paneFormulario.setForeground(new java.awt.Color(153, 153, 153));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codigo"));

        txtCodigo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtFechaInstalacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtFechaInstalacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Instalacion"));
        txtFechaInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInstalacionActionPerformed(evt);
            }
        });

        txtBarrio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBarrio.setBorder(javax.swing.BorderFactory.createTitledBorder("Barrio"));
        txtBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarrioActionPerformed(evt);
            }
        });

        txtCallePrincipal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCallePrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Calle Principal"));
        txtCallePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCallePrincipalActionPerformed(evt);
            }
        });

        txtCalleSecundaria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCalleSecundaria.setBorder(javax.swing.BorderFactory.createTitledBorder("Calle Secundaria"));
        txtCalleSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleSecundariaActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(150, 0));

        btnGuardar.setBackground(new java.awt.Color(52, 152, 219));
        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar32x32.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 40));

        btnCancelar.setBackground(new java.awt.Color(52, 152, 219));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar32x32.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setOpaque(true);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setPreferredSize(new java.awt.Dimension(150, 40));

        btnEliminar.setBackground(new java.awt.Color(52, 152, 219));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eliminar32x32.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setOpaque(true);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtMarca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtMarca.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca"));
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        txtNumeroCasa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNumeroCasa.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de Casa"));
        txtNumeroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCasaActionPerformed(evt);
            }
        });

        txtReferencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtReferencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Referencia"));
        txtReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReferenciaActionPerformed(evt);
            }
        });

        txtObservacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtObservacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Observación"));
        txtObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionActionPerformed(evt);
            }
        });

        txtSocio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtSocio.setBorder(javax.swing.BorderFactory.createTitledBorder("Socio"));
        txtSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneFormularioLayout = new javax.swing.GroupLayout(paneFormulario);
        paneFormulario.setLayout(paneFormularioLayout);
        paneFormularioLayout.setHorizontalGroup(
            paneFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFormularioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneFormularioLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addComponent(txtId)
                    .addComponent(txtCodigo)
                    .addComponent(txtFechaInstalacion)
                    .addComponent(txtBarrio)
                    .addComponent(txtCallePrincipal)
                    .addComponent(txtCalleSecundaria)
                    .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumeroCasa)
                    .addComponent(txtReferencia)
                    .addComponent(txtObservacion)
                    .addComponent(txtSocio))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        paneFormularioLayout.setVerticalGroup(
            paneFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFormularioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFechaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCallePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCalleSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 152, 219));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Inicio/Registros/Medidores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(paneFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(paneFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void inhabilitar() {
        isActiveNuevo = false;
        isActiveEditar = false;
        txtCodigo.setEditable(false);
        txtMarca.setEditable(false);
        txtFechaInstalacion.setEditable(false);
        txtCalleSecundaria.setEditable(false);
        txtCallePrincipal.setEditable(false);
        txtNumeroCasa.setEditable(false);
        txtReferencia.setEditable(false);
        txtBarrio.setEditable(false);
        btnGuardar.setBackground(new Color(179, 182, 183));
        btnEditar.setBackground(new Color(179, 182, 183));
        btnEliminar.setBackground(new Color(179, 182, 183));
        btnCancelar.setBackground(new Color(179, 182, 183));

    }

    private void habilitarNuevo() {
        isActiveNuevo = true;
        isActiveEditar = false;
        txtCodigo.setEditable(true);
        txtMarca.setEditable(true);
        txtFechaInstalacion.setEditable(true);
        txtCalleSecundaria.setEditable(true);
        txtCallePrincipal.setEditable(true);
        txtNumeroCasa.setEditable(true);
        txtReferencia.setEditable(true);
        txtBarrio.setEditable(true);
        btnGuardar.setBackground(new Color(52, 152, 219));
        btnEditar.setBackground(new Color(179, 182, 183));
        btnEliminar.setBackground(new Color(179, 182, 183));
        btnCancelar.setBackground(new Color(52, 152, 219));
    }

       private void tablahabilitareditar() {
         isActiveNuevo = true;
        isActiveEditar = true;
                txtCodigo.setEditable(false);
        txtMarca.setEditable(false);
        txtFechaInstalacion.setEditable(false);
        txtCalleSecundaria.setEditable(false);
        txtCallePrincipal.setEditable(false);
        txtNumeroCasa.setEditable(false);
        txtReferencia.setEditable(false);
        txtBarrio.setEditable(false);
        btnGuardar.setBackground(new Color(52, 152, 219));
        btnCancelar.setBackground(new Color(52, 152, 219));
        btnEditar.setBackground(new Color(52, 152, 219));
        btnEliminar.setBackground(new Color(52, 152, 219));
    }
    private void habilitareditar() {
         isActiveNuevo = true;
        isActiveEditar = true;
        txtCodigo.setEditable(true);
        txtMarca.setEditable(true);
        txtFechaInstalacion.setEditable(true);
        txtCalleSecundaria.setEditable(true);
        txtCallePrincipal.setEditable(true);
        txtNumeroCasa.setEditable(true);
        txtReferencia.setEditable(true);
        txtBarrio.setEditable(true);
        btnGuardar.setBackground(new Color(52, 152, 219));
        btnCancelar.setBackground(new Color(52, 152, 219));
        btnEditar.setBackground(new Color(52, 152, 219));
        btnEliminar.setBackground(new Color(52, 152, 219));
    }

    private void limpiarCampos() {
        txtId.setText("");
        txtCodigo.setText("");
        txtMarca.setText("");
        txtFechaInstalacion.setText("");
        txtCalleSecundaria.setText("");
        txtCallePrincipal.setText("");
        txtNumeroCasa.setText("");
        txtReferencia.setText("");
        txtBarrio.setText("");

    }

    void cargarTabla(String buscar, String criterioBusqueda, String criterioOrden, String orden) {
        try {
            DefaultTableModel modelo;
            fMedidores funcMedidores = new fMedidores();
            modelo = funcMedidores.mostrar(buscar, criterioBusqueda, criterioOrden, orden);
            tblMedidores.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }
       /* void cargarTablaMedidoresSocios(int idSocio) {
        try {
            DefaultTableModel modelo;
            fSocios funcSocios = new fSocios();
            modelo = funcSocios.mostrarMedidoresSocio(idSocio);
            tblMedidoresSocio.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }

    }
*/
    void guardar() {
        if (txtCodigo.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el código del medidor");
            txtCodigo.requestFocus();
            return;
        }
        if (txtMarca.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la marca del medidor");
            txtMarca.requestFocus();
            return;
        }

        if (txtFechaInstalacion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la fecha en la que se instaló el medidor");
            txtFechaInstalacion.requestFocus();
            return;
        }

        if (txtCalleSecundaria.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la calle secundaria de la ubicación del medidor");
            txtCalleSecundaria.requestFocus();
            return;
        }
                if (txtNumeroCasa.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el número de casa de la ubicación del medidor");
            txtCalleSecundaria.requestFocus();
            return;
        }
                                if (txtBarrio.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el barrio de la ubicación del medidor");
            txtBarrio.requestFocus();
            return;
        }
        if (txtCallePrincipal.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la calle principal de la ubicación del medidor");
            txtCallePrincipal.requestFocus();
            return;
        }

        if (txtReferencia.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar una referencia de la ubicación del medidor");
            txtReferencia.requestFocus();
            return;
        }

        clsMedidores dts = new clsMedidores();
        fMedidores funcMedidores = new fMedidores();
        dts.setCodigo(txtCodigo.getText());
        dts.setMarca(txtMarca.getText());
        dts.setFechaInstalacion(Date.valueOf(txtFechaInstalacion.getText()));
        dts.setBarrio(txtBarrio.getText());
        dts.setCalle_Principal(txtCallePrincipal.getText());
        dts.setCalle_Secundaria(txtCalleSecundaria.getText());
        dts.setNumero_Casa(txtNumeroCasa.getText());
        dts.setReferencia(txtReferencia.getText());
        dts.setObservacion(txtObservacion.getText());
        dts.setFkSocios(Integer.parseInt(txtSocio.getText()));
        if (accion.equals("nuevo")) {
            if (funcMedidores.insertar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "El socio se ha registrado satisfactoriamente");
                cargarTabla("", "Codigo", "Codigo", "desc");
                limpiarCampos();
                       isActiveEditar=false;
                   isActiveNuevo=false;
                   inhabilitar();
            }
        } else if (accion.equals("editar")) {
            try {
                dts.setId(Integer.parseInt(txtId.getText()));
                if (funcMedidores.editar(dts)) {
                    JOptionPane.showConfirmDialog(rootPane, "Se ha actualizado el registro del medidor " + dts.getMarca()+ " "+dts.getCodigo());
                    cargarTabla("", "Codigo", "Codigo", "desc");
                      isActiveEditar=false;
                   isActiveNuevo=false;
                   inhabilitar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error al actualizar el registro", "Error", JOptionPane.INFORMATION_MESSAGE, null);
            }
        }else if(accion.equals("null")){
                            JOptionPane.showMessageDialog(null, "Seleciona la opcion de actualizar registro primero", "Error", JOptionPane.INFORMATION_MESSAGE, null);

        }else{
            JOptionPane.showMessageDialog(null, "No se ha entendido  tu peticion", "Error", JOptionPane.INFORMATION_MESSAGE, null);
        }

    }
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
       txtMarca.transferFocus();
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
       if(isActiveNuevo||isActiveEditar){
               guardar();
       }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void tblMedidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedidoresMouseClicked
        int fila = tblMedidores.rowAtPoint(evt.getPoint());
        txtId.setText(tblMedidores.getValueAt(fila, 0).toString());
        txtSocio.setText(tblMedidores.getValueAt(fila, 1).toString());
        txtCodigo.setText(tblMedidores.getValueAt(fila, 2).toString());
        txtMarca.setText(tblMedidores.getValueAt(fila, 3).toString());
        txtFechaInstalacion.setText(tblMedidores.getValueAt(fila, 4).toString());
        txtBarrio.setText(tblMedidores.getValueAt(fila, 5).toString());
        txtCallePrincipal.setText(tblMedidores.getValueAt(fila, 6).toString());
        txtCalleSecundaria.setText(tblMedidores.getValueAt(fila, 7).toString());
        txtNumeroCasa.setText(tblMedidores.getValueAt(fila, 8).toString());
        txtReferencia.setText(tblMedidores.getValueAt(fila, 9).toString());
        txtObservacion.setText(tblMedidores.getValueAt(fila, 10).toString());
      
//       cargarTablaMedidoresSocios(Integer.parseInt(tblSocios.getValueAt(fila, 0).toString()));
        accion="null";
        isActiveEditar=true;
        tablahabilitareditar();
    }//GEN-LAST:event_tblMedidoresMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
if(isActiveEditar){
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un registro a editar", "Error", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            accion = "editar";
            habilitareditar();
        }
}
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
       if(isActiveEditar){
           eliminar();
       }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void eliminar(){
         if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un registro a eliminar", "Error", JOptionPane.INFORMATION_MESSAGE, null);
        } else {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro que deseas eliminar el registro", "Confirmar", 2);
            if (confirmacion == 0) {
                try {
                    fMedidores funcMedidores = new fMedidores();
                    clsMedidores dts = new clsMedidores();
                    dts.setId(Integer.parseInt(txtId.getText()));
                    funcMedidores.eliminar(dts);
                    JOptionPane.showMessageDialog(null, "Se ha eliminado el registro", "Éxito", JOptionPane.INFORMATION_MESSAGE, null);
                   limpiarCampos();
                   isActiveEditar=false;
                   isActiveNuevo=false;
                   inhabilitar();
                    cargarTabla("", "Codigo", "Codigo", "desc");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, " Ha ocurrido un error al eliminar el registro", "Error", JOptionPane.INFORMATION_MESSAGE, null);

                }
            }
        }
    }
    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked

    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       if(txtBuscar.getText().length()>0){
           ImageIcon iconoCancelarBusqueda=new ImageIcon("src/main/resources/cancelSoftnoBorder32x32.png");
           btnBuscar.setIcon( iconoCancelarBusqueda);
       }else{
           ImageIcon iconoBusqueda=new ImageIcon("src/main/resources/buscar32x32.png");
           btnBuscar.setIcon( iconoBusqueda);
       }
        String criterioBusqueda = "";
        //Código, Marca, Nombres Socio, Cedula Socio, Barrio, Calle Principal, Fecha Instalacion, Numero Casa

        if (cmbCategoria.getSelectedItem().toString().equals("Código")) {
            criterioBusqueda = "Codigo";
        }
        if (cmbCategoria.getSelectedItem().toString().equals("Marca")) {
            criterioBusqueda = "Marca";
        }
        if (cmbCategoria.getSelectedItem().toString().equals("Nombres Socio")) {
            criterioBusqueda = "fkSocios";
        }
        if (cmbCategoria.getSelectedItem().toString().equals("Cedula Socio")) {
            criterioBusqueda = "fkSocios";
        }
        if (cmbCategoria.getSelectedItem().toString().equals("Barrio")) {
            criterioBusqueda = "Barrio";
        }
         if (cmbCategoria.getSelectedItem().toString().equals("Calle Principal")) {
            criterioBusqueda = "Calle_Principal";
        }
          if (cmbCategoria.getSelectedItem().toString().equals("Fecha Instalacion")) {
            criterioBusqueda = "Fecha_Instalacion";
        }
          if (cmbCategoria.getSelectedItem().toString().equals("Numero Casa")) {
            criterioBusqueda = "Numero_Casa";
        }
        cargarTabla(txtBuscar.getText(), criterioBusqueda, criterioBusqueda, "desc");
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(133, 193, 233));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered
        btnReporte.setBackground(new Color(133, 193, 233));
    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(133, 193, 233));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(52, 152, 219));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(52, 152, 219));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        btnReporte.setBackground(new Color(52, 152, 219));
    }//GEN-LAST:event_btnReporteMouseExited

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        limpiarCampos();
        accion = "nuevo";
        habilitarNuevo();
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        if (isActiveEditar) {
            btnEditar.setBackground(new Color(133, 193, 233));
        }
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        if (isActiveNuevo||isActiveEditar) {
            btnGuardar.setBackground(new Color(133, 193, 233));
        }
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        if (isActiveNuevo||isActiveEditar) {
            btnCancelar.setBackground(new Color(133, 193, 233));
        }
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        if (isActiveEditar) {
            btnEliminar.setBackground(new Color(133, 193, 233));
        }
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        if (isActiveEditar) {
            btnEliminar.setBackground(new Color(52, 152, 219));
        }
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        if (isActiveNuevo||isActiveEditar) {
            btnCancelar.setBackground(new Color(52, 152, 219));
        }
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        if (isActiveNuevo||isActiveEditar) {
            btnGuardar.setBackground(new Color(52, 152, 219));
        }
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        if (isActiveEditar) {
            btnEditar.setBackground(new Color(52, 152, 219));
        }
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
   if(isActiveEditar||isActiveNuevo){
        limpiarCampos();
    inhabilitar();
    isActiveEditar=false;
    isActiveNuevo=false;
   }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
    txtCodigo.transferFocus();
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtFechaInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInstalacionActionPerformed
   txtFechaInstalacion.transferFocus();
    }//GEN-LAST:event_txtFechaInstalacionActionPerformed

    private void txtBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarrioActionPerformed
        txtBarrio.transferFocus();
    }//GEN-LAST:event_txtBarrioActionPerformed

    private void txtCallePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCallePrincipalActionPerformed
    txtCallePrincipal.transferFocus();
    }//GEN-LAST:event_txtCallePrincipalActionPerformed

    private void txtCalleSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleSecundariaActionPerformed
     txtCalleSecundaria.transferFocus();
    }//GEN-LAST:event_txtCalleSecundariaActionPerformed

    private void txtNumeroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCasaActionPerformed
     txtNumeroCasa.transferFocus();
    }//GEN-LAST:event_txtNumeroCasaActionPerformed

    private void txtReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaActionPerformed
   //En esta parte queria hacer que pase el Focus a el boton guardar :´)
    }//GEN-LAST:event_txtReferenciaActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
     if(txtBuscar.getText().isEmpty()){
                             JOptionPane.showMessageDialog(null, " Escribe un texto y selecciona la categoría a buscar", "Error", JOptionPane.INFORMATION_MESSAGE, null);

     }else{
         txtBuscar.setText("");
                  ImageIcon iconoBusqueda=new ImageIcon("src/main/resources/buscar32x32.png");
           btnBuscar.setIcon( iconoBusqueda);
        cargarTabla("", "Codigo", "Codigo", "desc");  
        cmbCategoria.setSelectedIndex(1);
     }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void txtBuscarInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBuscarInputMethodTextChanged

    }//GEN-LAST:event_txtBuscarInputMethodTextChanged

    private void txtObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionActionPerformed

    private void txtSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMedidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMedidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMedidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMedidores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMedidores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnReporte;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel paneFormulario;
    private javax.swing.JTable tblMedidores;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCallePrincipal;
    private javax.swing.JTextField txtCalleSecundaria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFechaInstalacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSocio;
    // End of variables declaration//GEN-END:variables
}
